### ISSUE TITLE
hf上面没有autoaudit_20230703_attempt2的权重下载不了

### ISSUE THREAD

**Issue by yinjiuzui** [ddzipp/AutoAudit#9]
python manage.py runserver
using cuda
device_map:  auto
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:12<00:00,  6.48s/it]
prompter and tokenizer is not None
<utils.prompter.Prompter object at 0x7f640ff21c00>
LlamaTokenizer(name_or_path='/root/autodl-tmp/AutoAudit/sandbox/yahma/llama-7b-hf', vocab_size=32000, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<unk>'}, clean_up_tokenization_spaces=False)
using cude
device_map:  auto
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:12<00:00,  6.14s/it]
using cuda
device_map:  auto
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.60s/it]
prompter and tokenizer is not None
<utils.prompter.Prompter object at 0x7f0d1892dba0>
LlamaTokenizer(name_or_path='/root/autodl-tmp/AutoAudit/sandbox/yahma/llama-7b-hf', vocab_size=32000, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<unk>'}, clean_up_tokenization_spaces=False)
using cude
device_map:  auto
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:12<00:00,  6.20s/it]
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/peft/utils/config.py", line 99, in from_pretrained
    config_file = hf_hub_download(pretrained_model_name_or_path, CONFIG_NAME)
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/root/autodl-tmp/AutoAudit/sandbox/AutoAudit/apps.py", line 201, in ready
    main_alpaca()
  File "/root/autodl-tmp/AutoAudit/sandbox/AutoAudit/apps.py", line 159, in main_alpaca
    AutoauditConfig.model = PeftModel.from_pretrained(
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/peft/peft_model.py", line 137, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[PeftConfig.from_pretrained(model_id).peft_type].from_pretrained(model_id)
  File "/root/miniconda3/envs/AutoAudit/lib/python3.10/site-packages/peft/utils/config.py", line 101, in from_pretrained
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'")
ValueError: Can't find 'adapter_config.json' at 'lilBuffaloEric/autoaudit_20230703_attempt2'
using cuda

**Comment by ddzipp** [comment]
I sincerely apologize for any inconvenience this may cause. I have already checked the Huggingface. The repo in Huggingface indeed contains the adapter_config.json file.
The error message mentions a "Connection error," which suggests that, despite the file being available in the repository, an unstable or interrupted network connection might prevent the model files from downloading successfully. Please check the server's network connection to ensure it can access the Hugging Face repository without interruptions. If you have any further questions, please feel free to ask.
By the way, we have updated latest model based on Llama3-8B-Instruct. You can use the latest model if you like.

**Comment by yinjiuzui** [comment]
好的，谢谢，已经解决了。需要将AutoAudit/sandbox/AutoAudit/apps.py文件改为本地路径
```
        def main_alpaca():
            '''
            load_8bit = True,
            base_model = "yahma/llama-7b-hf",
            lora_weights = "lilBuffaloEric/autoaudit_20230703_attempt2",
            prompt_template = "",  # The prompt template to use, will default to alpaca.
            server_name = "0.0.0.0",  # Allows to listen on all interfaces by providing '0.
            share_gradio = False,'''
            load_8bit = True;
            base_model = "yahma/llama-7b-hf";
            lora_weights = "lilBuffaloEric/autoaudit_20230703_attempt2";
            prompt_template = "";  # The prompt template to use, will default to alpaca.
            server_name = "0.0.0.0";  # Allows to listen on all interfaces by providing '0.
            share_gradio = False;
```
